{% set name = "napari-rioxarray" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-rioxarray-{{ version }}.tar.gz
  sha256: 2831a8677650be382336bc73cdd2879b1aa4f4ef2f4d586ef79135bc99dcf990

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - napari
    - numpy
    - python >=3.8
    - rioxarray

test:
  imports:
    - napari_rioxarray
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AndrewAnnex/napari-rioxarray
  summary: A rioxarray plugin for napari supporting GDAL raster datatypes
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AndrewAnnex
    - goanpeca
    - jaimergp
